#!/bin/bash

echo -e "Sisesta ridade arv: \c "
read rida
for (( i=1; i <= $rida; i++))
do
   echo -n "$i. "
   for (( j = 1 ; j <= $i; j++))
   do
          echo -n "* "
   done
  echo "" ##### print the new line ###
done

