#!/bin/bash

echo -n " Sisesta ainepunktide arv:"
read ainepunktid 
echo -n " Sisesta nädalate arv:"
read nadalad 
aeg=`echo "scale=1;78/10" | bc`
echo $aeg
aeg_ymarda="`echo "($aeg+0.9)/1" | bc`"
echo $aeg_ymarda
