#!/bin/bash

#Loeb aja vaartuse ja kasutaja nime automaatselt ja väljastab need

VAR_1="$(whoami)"
aeg=$(date +"%H")
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
echo " Tere hommikust, ${VAR_1^}!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
echo "Tere paevast, ${VAR_1^}!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
echo "Tere ohtust, ${VAR_1^}!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
echo "Head ood, ${VAR_1^}!"
fi


