#!/bin/bash

#reisi korraldamine

#inimeste anded
echo -n "Sisesta reisijate arv: "
read reisijad
#kohtade andmed bussis
echo -n "Sisesta kohtade arv bussis: "
read kohad

# arvutused

#jagame inimested busside vahel nii, et koik kohad bussides oleks taidetud - sellega
#saame teada, palju busse vaja on
bussid=$(($reisijad / $kohad))
#vaatame, palju on neid, kes ei saanud kohta bussides - need on yle jaanud reisijad,
#ehk jaagid, kui koik kohad on taidetud
ylejaanud=$(($reisijad % $kohad))
#kui on olemas ylejaanud, tuleb suurendada busside arv 1 vorra
if test $ylejaanud -gt 0
then
#bussid muutuja vaja uledefineerimist, selle parast umbersalvestamiseks
#ei kasuta $ marki, aga arvutamisel juba kasutame
 bussid=$(($bussid + 1))
fi
#tulemuste valjastamine
echo "Kokku on vaja $bussid taisbussi"
#skripti lopp
