#!/bin/bash

#Alroritm:
#kui kasureaparameetrite arv ei vordu 1-ga;siis truki valja selgituslause
#muidu
#esimene parameeter on arv
#arvuta, kas ta on paaris voi paaritu
#valjasta tulemus
#--------------------------------
if [ $# -ne 1 ]; then
  echo "Kaivita see skript koos arvuga mille paarsus soovid kontrollida. Naiteks: $0 3"
else
arv=$1
jaak=$(( $arv % 2 ))
if [ $jaak -eq 0 ]; then
echo "$arv on paaris"
else
echo "$arv on paaritu"
fi
fi
